name: HyperEncoder CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Create working file
      run: ./create_working_file.sh

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: HyperEncoder
        path: HyperEncoder.zip
